# SPDX-FileCopyrightText: 2011-2026 Joe T. Sylve, Ph.D. <joe.sylve@gmail.com>
# SPDX-License-Identifier: GPL-2.0-only

version = 1

[[annotations]]
path = [
    "README.md",
    "doc/README.md",
    "doc/external_modules.md",
    ".gitignore",
    ".github/FUNDING.yml",
    ".github/workflows/pre-commit.yml",
    ".pre-commit-config.yaml",
]
SPDX-FileCopyrightText = "2011-2026 Joe T. Sylve, Ph.D. <joe.sylve@gmail.com>"
SPDX-License-Identifier = "GPL-2.0-only"
