# SPDX-FileCopyrightText: 2011-2026 Joe T. Sylve, Ph.D. <joe.sylve@gmail.com>
# SPDX-License-Identifier: GPL-2.0-only

version = 1

[[annotations]]
path = [
    "README.md",
    "docs/README.md",
    "docs/external_modules.md",
    ".gitignore",
    ".github/FUNDING.yml",
    ".github/workflows/pre-commit.yml",
    ".pre-commit-config.yaml",
    ".github/workflows/build-test.yml",
    "docs/test-architecture.md",
    "test/Dockerfile",
    "test/kernel-versions.conf",
]
SPDX-FileCopyrightText = "2011-2026 Joe T. Sylve, Ph.D. <joe.sylve@gmail.com>"
SPDX-License-Identifier = "GPL-2.0-only"
